### ISSUE TITLE
How do I set the x-axis for dose response curve?

### ISSUE THREAD

**Issue by kennyyeo13** [TangSoftwareLab/SynergyFinderR#4]
Hi, 
I am pretty new to R. I just wanted to check how do I change the range for x-axis?  

Thanks
Kenny

**Comment by shuyuzheng** [comment]
I have updated the "PlotDoseResponseCurve" function in version 3.4.2 to enable the changing of x-axis for users. Now you can update the package to 3.4.2 and then use the parameter "xlim" to control the range for x-axis. The command looks like:
`PlotDoseResponseCurve(data = [data_list], xlim = c([min_x], [max_x]))`
